Remove uneeded flake-utils, improve derivation
Dawoox/EpiFunctionChecker pull request #3
Opened 2023-11-29 19:05 UTC by Sigmanificient

2023-11-29 19:09 UTC, Sigmanificient commented
![image](https://github.com/Dawoox/efc/assets/53050011/fcb9cc05-0bcd-4df9-8afc-d2bd8226c34a)

2023-11-30 08:44 UTC, Dawoox requested changes
This typo should be fix before merging

2023-11-30 08:44 UTC, Dawoox commented on flake.nix
> +          defulat = EpiFunctionChecker;
Possible typo ? Should that be `default`

2023-11-30 12:32 UTC, Sigmanificient commented on flake.nix
> +          defulat = EpiFunctionChecker;
```suggestion
          default = EpiFunctionChecker;
```

2023-11-30 13:38 UTC, Dawoox approved these changes
Everything seems right to me

2023-11-30 13:40 UTC, merged